Fix build error: Cannot find module './routes/routes.v1'
It was all because I hadn't committed the routes file into git... SMH!
Let's see how this goes...

[#170020608]