Try to fix build error: Cannot find module './routes/routes.v1'
Travis CI gives an error during build process. Not sure whether it's
because of the naming convention, or because of Node version, so I'll just
try different fixes.

[#170020608]